# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I'm homesangsang # ex. I m Chuan
name: homesangsang # ex. DONGChuan
email: homesangsang@163.com
location: My location # ex. Nice, France
company:  Beijing ChengQiTong Technology Co., Ltd. 
company_url: http://www.linkcircle.cn/
github_url: https://github.com/homesangsang # ex. https://github.com/DONGChuan
github_username: homesangsang # ex. DONGChuan
description: I don't know
favicon: favicon.png # Image must be in assets/images
repository: homesangsang/homesangsang.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: homesangsang.github.io # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 20
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, MySQL, SQLite, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJ, Redis, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
